bio: >
    Alex Wallar is a PhD student in the Computer Science and Artificial Intelligence Lab at MIT. His research focusses on optimizing vehicle distributions and fleet sizes for ride-sharing systems to maximize system performance. He is a recipient of the Lemelson Presidential Fellowship, the MIT Diversity Fellowship, and the Shell-MIT Energy Fellowship. He received his masters degree in electrical engineering and computer science from MIT in 2017 with a focus on applications of constrained optimization for mobility-on-demand systems. He received is bachelors degree in computer science from the University of St Andrews in 2015 with first class honours.

bio_image: imgs/me-new.jpg

position: PhD Student at MIT

blurb: Interested in autonomous systems and urban mobility

projects:
    - name: On-demand high-capacity ride-sharing
      links:
        - link: http://www.pnas.org/content/early/2017/01/01/1611675114
          title: PNAS
          type: pub
        - link: http://alonsomora.com/docs/18-wallar-iros.pdf
          title: IROS 2018
          type: pub
        - link: http://motherboard.vice.com/read/3000-ubers-could-replace-nycs-entire-taxi-fleet
          title: VICE Magazine
          type: news
        - link: http://money.cnn.com/2017/01/02/technology/mit-taxis-new-york/index.html
          title: CNN
          type: news
        - link: http://www.bbc.co.uk/news/technology-38496175
          title: BBC
          type: news
        - link: http://fortune.com/2017/01/03/uber-lyft-carpooling/
          title: Fortune
          type: news
        - link: http://europe.newsweek.com/uber-new-york-traffic-taxi-mit-study-537925
          title: Newsweek
          type: news
        - link: http://www.theverge.com/2017/1/2/14147286/mit-research-nyc-taxi-carpool-uber-lyft
          title: The Verge
          type: news
        - link: https://www.ft.com/content/b56b44a6-ceab-11e6-864f-20dcb35cede2
          title: Financial Times
          type: news
        - link: http://gizmodo.com/rideshare-carpooling-could-completely-eliminate-the-nee-1790623953
          title: Gizmodo
          type: news
        - link: http://www.popularmechanics.com/cars/technology/a24567/mit-taxi-algorithm/
          title: Popular Mechanics
          type: news
        - link: https://www.washingtonpost.com/news/dr-gridlock/wp/2017/01/02/study-3000-ubers-could-replace-new-york-citys-taxi-fleet-if-youre-willing-to-share/?utm_term=.6708692876b8
          title: Washington Post
          type: news
        - link: https://www.washingtonpost.com/news/dr-gridlock/wp/2017/01/02/study-3000-ubers-could-replace-new-york-citys-taxi-fleet-if-youre-willing-to-share/?utm_term=.0028098455e6
          title: Engadget
          type: news
      image: imgs/mod.png

    - name: Multi-class fleet sizing for mobility-on-demand
      links:
        - link: /publications/wallar-icra-fleet-2019.pdf
          title: ICRA 2019
          type: pub
      image: imgs/fleet-sizing.png

    - name: Remote sensing for autonomous vehicles with UAVs
      links:
        - link: /publications/17-wallar-FSR.pdf
          title: FSR 2017
          type: pub
        - link: https://www.youtube.com/watch?v=IRhWPcHZmuU
          title: Demo
          type: video
      image: imgs/foresight.jpg

    - name: Risk sensitive surveillance using unmanned aerial vehicles
      links:
        - link: /publications/WallarPlakuSofge.pdf
          title: T-ASE 2015
          type: pub
        - link: /publications/SIS14-PARCov.pdf
          title: SSCI 2014
          type: pub
      image: imgs/avoid_risk_swarm.png

    - name: Path planning for swarms in dynamic environments
      links:
        - link: /publications/SIS14-dCRoPS.pdf
          title: SSCI 2014
          type: pub
        - link: /publications/TAROS2013.pdf
          title: TAROS 2013
          type: pub
      image: imgs/dCRoPS.jpg

    # - title: >
    #     Generating safe trajectories in dynamic environments by leveraging
    #     information about obstacle motion
    #   links:
    #     - link: /publications/st-andrews-thesis.pdf
    #       title: Undergraduate Thesis
    #   image: imgs/dodger.png
    #   name: Dodger
